a=10
print("a=",a,"datatype",type(a))
b=20.30
print("b=",b,"datatype",type(b))
c=3+2j
print("c=",c,"datatype",type(c))
str="rlsbca"
print("String=",str,"datatype",type(str))
ls=["amit",12,23.4,True]
print("list=",ls,"datatype=",type(ls))
tp=("aditi","manasvi","arpita")
print("tuple=",tp,"datatype=",type(tp))
d=True
print("boolean=",d,"datatype",type(d))
dic={1:"apple",2:"ball"}
print("dictionary=",dic,"datatype=",type(dic)) 
set={1,2,3,4}
print("set=",set,"datatype",type(set))